[project]
name = "naiprojekt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tensorflow==2.12.0",
    "keras==2.12.0",
    "matplotlib>=3.10.0",
    "numpy>=1.22.0,<1.24.0",
    "pre-commit>=4.0.1",
    "scipy==1.11.4",
    "pillow>=10.0.0",
    "openai>=1.0.0",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "tk>=0.1.0",
    "tqdm>=4.66.1",
    "pandas>=2.1.4",
    "scikit-learn>=1.3.2",
    "reportlab>=4.0.0",
]

[tool.pydocstyle]
convention = "google"
add-ignore = ["D100", "D104"]

[project.optional-dependencies]
dev = [
    "black>=23.12.1",
    "isort>=5.13.2",
    "mypy>=1.8.0",
    "flake8>=7.0.0",
    "pytest>=7.0.0"
]

[tool.poetry.dependencies]
python = "^3.8"
tensorflow = "2.12.0"
